# IMPORTANT: THESE SECRETS ARE ONLY FOR DEVELOPMENT
apiVersion: v1
kind: Secret
metadata:
  name: spa-backend-secret
  namespace: layer8
type: Opaque
stringData:
  HOST: "0.0.0.0"
  PORT: "3000"
  JWT_SECRET: "spa-backend-jwt-secret"
  LAYER8_URL: "http://auth-server.layer8.svc.cluster.local:5001"
  LAYER8_CALLBACK_URL: "http://spa-frontend-sp1.layer8.svc.cluster.local:5173/oauth2/callback"
  LAYER8_RESOURCE_URL: "http://auth-server.layer8.svc.cluster.local:5001/api/user"
  LAYER8_UUID: "7bb3f7db-481e-446a-b69d-0c3e6388f289"
  LAYER8_SECRET: "4f078b75725c5f17591011bd18ec6abf"
  NODE_ENV: "development"
