apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-sp1
  namespace: layer8
  labels:
    app: reverse-proxy-sp1
spec:
  type: NodePort
  ports:
  - port: 6193
    targetPort: 6193
    nodePort: 30193
    protocol: TCP
    name: http
  selector:
    app: reverse-proxy-sp1