# IMPORTANT: THESE SECRETS ARE ONLY FOR DEVELOPMENT
apiVersion: v1
kind: Secret
metadata:
  name: auth-setup-secrets
  namespace: layer8
  labels:
    app: auth-server
    component: secrets
type: Opaque
stringData:
  # Server Configuration
  SERVER_PORT: "5001"
  
  # Secret Keys
  UP_999_SECRET_KEY: "secret_999"
  MP_123_SECRET_KEY: "secret_123"
  JWT_SECRET_KEY: "ThisIsASecret"
  
  # Database Configuration
  DB_NAME: "development"
  DB_HOST: "postgres.layer8.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "layer8development"
  DB_PASSWORD: "cRACtIeRChYsiNFinuMp"
  SSL_MODE: "disable"
  
  # Proxy Configuration
  PROXY_URL: "http://auth-server.layer8.svc.cluster.local:5001"
  TEST_CLIENT_BACKEND_URL: "reverse-proxy-sp1.layer8.svc.cluster.local:6193"
  
  # Email Configuration (MailerSend)
  MAILER_SEND_TEMPLATE_ID: "v69oxl517mz4785k"
  LAYER8_EMAIL_USERNAME: "info"
  LAYER8_EMAIL_DOMAIN: "layer8proxy.net"
  VERIFICATION_CODE_VALIDITY_DURATION: "10m"
  
  # ZK-SNARKs Configuration
  GENERATE_NEW_ZK_SNARKS_KEYS: "true"
  
  # InfluxDB Configuration
  INFLUXDB_URL: "http://influxdb.layer8.svc.cluster.local:8086"
  INFLUXDB_URL_TELEGRAF: "http://influxdb.layer8.svc.cluster.local:8086"
  INFLUXDB_USERNAME: "admin"
  INFLUXDB_PASSWORD: "somethingthatyoudontknow"
  INFLUXDB_ORG: "layer8"
  INFLUXDB_BUCKET: "layer8"
  INFLUXDB_TOKEN: "DEFAULT_TOKEN_FOR_TESTING"
  
  # OpenTelemetry Configuration
  OTEL_EXPORTER_OTLP_ENDPOINT: "auth-server.layer8.svc.cluster.local:4317"
  
  # Test User Configuration
  CREATE_TEST_USER: "true"
  TEST_USER_EMAIL: "test@layer8proxy.net"
  TEST_USER_PASSWORD: "12341234"
  TEST_USER_USERNAME: "tester"
  TEST_USER_FIRST_NAME: "john"
  TEST_USER_LAST_NAME: "doe"
  TEST_USER_DISPLAY_NAME: "john"
  TEST_USER_COUNTRY: "antartica"
  
  # Test Client Configuration
  CREATE_TEST_CLIENT: "true"
  TEST_CLIENT_NAME: "layer8"
  TEST_CLIENT_USERNAME: "layer8"
  TEST_CLIENT_PASSWORD: "12341234"
  TEST_CLIENT_REDIRECT_URI: "http://spa-frontend-sp1.layer8.svc.cluster.local:5173/oauth2/callback"
  TEST_CLIENT_BACKEND_URI: "http://reverse-proxy-sp1.layer8.svc.cluster.local:6193"
  
  # SCRAM Configuration
  SCRAM_ITERATION_COUNT: "4096"
  
  # Smart Contract Configuration
  SMART_CONTRACT_ADDRESS: "0x5D3c62CD23ED2C46463C9F8B5DadC1e63EB95973"
  
  # Usage Statistics Configuration
  UPDATE_CLIENT_USAGE_STATISTICS_TIME_INTERVAL: "2m"
  CLIENT_TRAFFIC_RATE_PER_BYTE: "5"
  
  # WebSocket Configuration (Polygon Alchemy)
  WEBSOCKET_NODE_URL: "wss://polygon-mainnet.g.alchemy.com/v2/dkGaa37QGa5qLAb4p6t0k0aF1YnSb45L"
  
  # Migration Path
  DB_SETUP_MIGRATION_PATH: "./migrations"