apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-https-lb
  namespace: layer8
  labels:
    app: reverse-proxy-https
spec:
  type: LoadBalancer
  ports:
  - port: 6193
    targetPort: 6193
    protocol: TCP
    name: https
  selector:
    app: reverse-proxy-https
