apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy-lb
  namespace: layer8
  labels:
    app: reverse-proxy-sp1
  annotations:
    networking.gke.io/managed-certificates: "reverse-proxy-cert"
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 6193
    protocol: TCP
    name: http
  - port: 443
    targetPort: 6193
    protocol: TCP
    name: https
  - port: 6193
    targetPort: 6193
    protocol: TCP
    name: proxy

  selector:
    app: reverse-proxy-sp1
