apiVersion: v1
kind: Service
metadata:
  name: spa-frontend-sp1
  namespace: layer8
  labels:
    app: spa-frontend-sp1
    sp-id: sp1
spec:
  type: NodePort
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30173
    protocol: TCP
    name: http
  selector:
    app: spa-frontend-sp1
