kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: layer8-dev-001
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # Forward Proxy
      - containerPort: 30191
        hostPort: 6191
        protocol: TCP
      # Reverse Proxy
      - containerPort: 30193
        hostPort: 6193
        protocol: TCP
      # Auth Server
      - containerPort: 30001
        hostPort: 5001
        protocol: TCP
      # SPA Frontend
      - containerPort: 30173
        hostPort: 5173
        protocol: TCP
      # SPA Backend
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      # InfluxDB
      - containerPort: 30086
        hostPort: 8086
        protocol: TCP
      # PostgreSQL
      - containerPort: 30432
        hostPort: 5432
        protocol: TCP
      # Ingress HTTP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # Ingress HTTPS
      - containerPort: 443
        hostPort: 443
        protocol: TCP
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/16"
