# IMPORTANT: THESE SECRETS ARE ONLY FOR DEVELOPMENT
apiVersion: v1
kind: Secret
metadata:
  name: spa-frontend-secret
  namespace: layer8
type: Opaque
stringData:
  HOST: "0.0.0.0"
  PORT: "5173"
  # VITE_BACKEND_URL: "http://35.206.202.18:6193"
  VITE_BACKEND_URL: "https://rpdev.gc.layer8proxy.net"
  # VITE_FORWARD_PROXY_URL: "http://35.206.255.157:6191"
  VITE_FORWARD_PROXY_URL: "https://fpdev.gc.layer8proxy.net"
