# IMPORTANT: THESE SECRETS ARE ONLY FOR DEVELOPMENT
apiVersion: v1
kind: Secret
metadata:
  name: spa-backend-secret
  namespace: layer8
type: Opaque
stringData:
  HOST: "0.0.0.0"
  PORT: "3000"
  JWT_SECRET: "spa-backend-jwt-secret"
  # LAYER8_URL: "http://35.206.226.108:5001"
  LAYER8_URL: "https://authdev.gc.layer8proxy.net"
  # LAYER8_CALLBACK_URL: "http://35.206.255.121:5173/oauth2/callback"
  LAYER8_CALLBACK_URL: "https://authdev.gc.layer8proxy.net/oauth2/callback"
  # LAYER8_RESOURCE_URL: "http://35.206.226.108:5001/api/user"
  LAYER8_RESOURCE_URL: "https://authdev.gc.layer8proxy.net/api/user"
  LAYER8_UUID: "74401057-67e9-49b3-9571-76bcbb168e80"
  LAYER8_SECRET: "5db563e7fe8cb96d8f07c272c966be5b"
  NODE_ENV: "development"
