apiVersion: v1
kind: Service
metadata:
  name: spa-frontend-sp1
  namespace: layer8
  labels:
    app: spa-frontend-sp1
    sp-id: sp1
spec:
  type: LoadBalancer
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
    name: default 
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
  - port: 443
    targetPort: 5173
    protocol: TCP
    name: https
  selector:
    app: spa-frontend-sp1
