# IMPORTANT: THESE SECRETS ARE ONLY FOR DEVELOPMENT
apiVersion: v1
kind: Secret
metadata:
  name: spa-frontend-secret
  namespace: layer8
type: Opaque
stringData:
  HOST: "0.0.0.0"
  PORT: "5173"
  VITE_BACKEND_URL: "http://reverse-proxy-sp1.layer8.svc.cluster.local:6193"
  VITE_FORWARD_PROXY_URL: "http://forward-proxy.layer8.svc.cluster.local:6191"