apiVersion: v1
kind: Service
metadata:
  name: forward-proxy
  namespace: layer8
  labels:
    app: forward-proxy
spec:
  type: NodePort
  ports:
  - port: 6191
    targetPort: 6191
    protocol: TCP
    name: http
  selector:
    app: forward-proxy
