# issuer-lets-encrypt-staging.yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-forward-proxy
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wasath.vt@gmail.com
    profile: tlsserver
    privateKeySecretRef:
      name: letsencrypt-forward-proxy
    solvers:
    - http01:
        ingress:
          name: forward-proxy-ingress